import type { WordEntry } from "./types";

export const WORDS: WordEntry[] = [
  { category: "Comida chilena", word: "completo" },
  { category: "Comida chilena", word: "sopaipilla" },
  { category: "Comida chilena", word: "empanada" },
  { category: "Comida chilena", word: "mote" },
  { category: "Comida chilena", word: "choripan" },
  { category: "Comida chilena", word: "marraqueta" },
  { category: "Comida chilena", word: "churrasco" },
  { category: "Comida chilena", word: "choclo" },
  { category: "Comida chilena", word: "cazuela" },
  { category: "Comida chilena", word: "terremoto" },
  { category: "Comida chilena", word: "humita" },
  { category: "Comida chilena", word: "charquican" },
  { category: "Comida chilena", word: "porotos" },
  { category: "Comida chilena", word: "pebre" },
  { category: "Comida chilena", word: "milcao" },
  { category: "Lugares de Chile", word: "santiago" },
  { category: "Lugares de Chile", word: "valparaiso" },
  { category: "Lugares de Chile", word: "vina" },
  { category: "Lugares de Chile", word: "iquique" },
  { category: "Lugares de Chile", word: "arica" },
  { category: "Lugares de Chile", word: "chiloe" },
  { category: "Lugares de Chile", word: "atacama" },
  { category: "Lugares de Chile", word: "maipo" },
  { category: "Lugares de Chile", word: "moneda" },
  { category: "Lugares de Chile", word: "mapocho" },
  { category: "Lugares de Chile", word: "antofagasta" },
  { category: "Lugares de Chile", word: "concepcion" },
  { category: "Lugares de Chile", word: "temuco" },
  { category: "Lugares de Chile", word: "pucon" },
  { category: "Lugares de Chile", word: "coyhaique" },
  { category: "Modismos chilenos", word: "altiro" },
  { category: "Modismos chilenos", word: "bacan" },
  { category: "Modismos chilenos", word: "fome" },
  { category: "Modismos chilenos", word: "carrete" },
  { category: "Modismos chilenos", word: "pololo" },
  { category: "Modismos chilenos", word: "copucha" },
  { category: "Modismos chilenos", word: "cachai" },
  { category: "Modismos chilenos", word: "yapo" },
  { category: "Modismos chilenos", word: "po" },
  { category: "Modismos chilenos", word: "luca" },
  { category: "Modismos chilenos", word: "quina" },
  { category: "Modismos chilenos", word: "pato" },
  { category: "Modismos chilenos", word: "cuico" },
  { category: "Modismos chilenos", word: "piola" },
  { category: "Modismos chilenos", word: "latero" },
  { category: "Objetos cotidianos", word: "mochila" },
  { category: "Objetos cotidianos", word: "celular" },
  { category: "Objetos cotidianos", word: "micro" },
  { category: "Objetos cotidianos", word: "carnet" },
  { category: "Objetos cotidianos", word: "parrilla" },
  { category: "Objetos cotidianos", word: "volantin" },
  { category: "Objetos cotidianos", word: "pelota" },
  { category: "Objetos cotidianos", word: "bicicleta" },
  { category: "Objetos cotidianos", word: "computador" },
  { category: "Objetos cotidianos", word: "audifonos" },
  { category: "Objetos cotidianos", word: "bip" },
  { category: "Objetos cotidianos", word: "termo" },
  { category: "Objetos cotidianos", word: "llavero" },
  { category: "Objetos cotidianos", word: "zapatillas" },
  { category: "Objetos cotidianos", word: "mascarilla" },
  { category: "Cultura chilena", word: "cueca" },
  { category: "Cultura chilena", word: "ramada" },
  { category: "Cultura chilena", word: "fonda" },
  { category: "Cultura chilena", word: "huaso" },
  { category: "Cultura chilena", word: "china" },
  { category: "Cultura chilena", word: "organillero" },
  { category: "Cultura chilena", word: "chinchinero" },
  { category: "Cultura chilena", word: "condorito" },
  { category: "Cultura chilena", word: "copihue" },
  { category: "Cultura chilena", word: "bandera" },
  { category: "Cultura chilena", word: "rodeo" },
  { category: "Cultura chilena", word: "feria" },
  { category: "Cultura chilena", word: "minga" },
  { category: "Cultura chilena", word: "payador" },
  { category: "Cultura chilena", word: "tonada" },
  { category: "Carrete", word: "piscola" },
  { category: "Carrete", word: "asado" },
  { category: "Carrete", word: "karaoke" },
  { category: "Carrete", word: "previa" },
  { category: "Carrete", word: "parrillada" },
  { category: "Carrete", word: "jenga" },
  { category: "Carrete", word: "cerveza" },
  { category: "Carrete", word: "hielera" },
  { category: "Carrete", word: "vaso" },
  { category: "Carrete", word: "parlante" },
  { category: "Carrete", word: "playlist" },
  { category: "Carrete", word: "baile" },
  { category: "Carrete", word: "brindis" },
  { category: "Carrete", word: "cotillon" },
  { category: "Carrete", word: "picoteo" },
  { category: "Colegio/universidad", word: "clase" },
  { category: "Colegio/universidad", word: "prueba" },
  { category: "Colegio/universidad", word: "recreo" },
  { category: "Colegio/universidad", word: "casino" },
  { category: "Colegio/universidad", word: "ramo" },
  { category: "Colegio/universidad", word: "fotocopia" },
  { category: "Colegio/universidad", word: "cuaderno" },
  { category: "Colegio/universidad", word: "profesor" },
  { category: "Colegio/universidad", word: "pase" },
  { category: "Colegio/universidad", word: "biblioteca" },
  { category: "Colegio/universidad", word: "calculadora" },
  { category: "Colegio/universidad", word: "laboratorio" },
  { category: "Colegio/universidad", word: "certamen" },
  { category: "Colegio/universidad", word: "uniforme" },
  { category: "Colegio/universidad", word: "colacion" },
  { category: "Tecnologia/startups", word: "startup" },
  { category: "Tecnologia/startups", word: "pitch" },
  { category: "Tecnologia/startups", word: "notebook" },
  { category: "Tecnologia/startups", word: "qr" },
  { category: "Tecnologia/startups", word: "wifi" },
  { category: "Tecnologia/startups", word: "webpay" },
  { category: "Tecnologia/startups", word: "transbank" },
  { category: "Tecnologia/startups", word: "redcompra" },
  { category: "Tecnologia/startups", word: "claveunica" },
  { category: "Tecnologia/startups", word: "rut" },
  { category: "Tecnologia/startups", word: "pantalla" },
  { category: "Tecnologia/startups", word: "usb" },
  { category: "Tecnologia/startups", word: "teclado" },
  { category: "Tecnologia/startups", word: "servidor" },
  { category: "Tecnologia/startups", word: "cowork" },
  { category: "Deportes", word: "roja" },
  { category: "Deportes", word: "futbol" },
  { category: "Deportes", word: "arco" },
  { category: "Deportes", word: "tenis" },
  { category: "Deportes", word: "surf" },
  { category: "Deportes", word: "ciclismo" },
  { category: "Deportes", word: "medalla" },
  { category: "Deportes", word: "baby" },
  { category: "Deportes", word: "raqueta" },
  { category: "Deportes", word: "arquero" },
  { category: "Deportes", word: "maraton" },
  { category: "Deportes", word: "camiseta" },
  { category: "Deportes", word: "skatepark" },
  { category: "Deportes", word: "cerro" },
  { category: "Deportes", word: "estadio" },
  { category: "Animales/cosas dibujables", word: "condor" },
  { category: "Animales/cosas dibujables", word: "pudu" },
  { category: "Animales/cosas dibujables", word: "huemul" },
  { category: "Animales/cosas dibujables", word: "llama" },
  { category: "Animales/cosas dibujables", word: "zorro" },
  { category: "Animales/cosas dibujables", word: "pinguino" },
  { category: "Animales/cosas dibujables", word: "ballena" },
  { category: "Animales/cosas dibujables", word: "caballo" },
  { category: "Animales/cosas dibujables", word: "quiltro" },
  { category: "Animales/cosas dibujables", word: "gato" },
  { category: "Animales/cosas dibujables", word: "palmera" },
  { category: "Animales/cosas dibujables", word: "montana" },
  { category: "Animales/cosas dibujables", word: "ola" },
  { category: "Animales/cosas dibujables", word: "fogata" },
  { category: "Animales/cosas dibujables", word: "estrella" },
];

export function pickRandomWord(excludedWords: string[] = []): WordEntry {
  const excluded = new Set(excludedWords.map((word) => word.toLowerCase()));
  const candidates = WORDS.filter((entry) => !excluded.has(entry.word.toLowerCase()));
  const pool = candidates.length > 0 ? candidates : WORDS;

  return pool[Math.floor(Math.random() * pool.length)];
}

export function pickWordChoices(count: number, excludedWords: string[] = []): WordEntry[] {
  const excluded = new Set(excludedWords.map((word) => word.toLowerCase()));
  const primaryPool = WORDS.filter((entry) => !excluded.has(entry.word.toLowerCase()));
  const pool = primaryPool.length >= count ? primaryPool : WORDS;
  const choices: WordEntry[] = [];
  const used = new Set<string>();

  while (choices.length < count && used.size < pool.length) {
    const candidate = pool[Math.floor(Math.random() * pool.length)];

    if (!used.has(candidate.word)) {
      choices.push(candidate);
      used.add(candidate.word);
    }
  }

  return choices;
}
